#Flask imports
from flask import Flask, render_template, send_file, make_response, url_for, Response,request,flash, redirect
from datetime import datetime,timedelta
from cProfile import label
import pandas as pd
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
import yfinance as yf
import numpy as np
from matplotlib import pyplot as plt
from pandas.plotting import scatter_matrix
import matplotlib.patches as patches
from matplotlib import font_manager
import io
import base64

fontP = font_manager.FontProperties()
fontP.set_family('SimHei')
fontP.set_size(14)

app = Flask(__name__)
# routes
@app.route('/index', methods=['POST','GET'])
def build_index():
    return render_template('index.html')
@app.route('/plot', methods=['POST','GET'])


def build_plot():
    select = request.form.get('StockCodeSelect')
    if not str(select):
         name = list[0].code 
    else:
        name = str(select)
    fig = plt.figure()

    stock = yf.Ticker(name)
    
    # tickers = yf.Tickers('msft aapl goog')

    data = yf.download(name, start=datetime.now() - timedelta(days=5*365), end=datetime.now())
    # data = yf.download("SPY AAPL", start="2017-01-01", end="2017-04-30")

    # show actions (dividends, splits)
    stock.actions
    # print(sunway.major_holders)
    # print(institutional_holders)

    # show dividends
    # print(sunway.dividends)
    # print(sunway.dividends)

    # show splits
    # print(sunway.splits)

    # print(stock.recommendations)

    # data['Open'].plot(label = 'Share price')
    # data['Volume'].plot(label = 'Volume')
    # plt.plot(sunway.dividends)
    # plt.title('Sunway share price & dividends')
    # plt.show()

    data['MA50'] = data['Open'].rolling(50).mean()
    data['MA200'] = data['Open'].rolling(200).mean()
    data['Open'].plot(figsize = (15,7), label="price")
    data['MA50'].plot(label="MA50")
    data['MA200'].plot(label="MA200")
    plt.title('Stock Prices and Moving Average of ' + stock.info['shortName'])
    # plt.text(1000, 1000,'addedsdf sfsdfasdfas fas fasd fasddfas fasd fasd f'
    # plt.text(0.5, 0.5, "Hello World!") 
    plt.legend()

    # plt.show()

    # print(data['MA50'][-1])
    # print(data['MA200'][-1])
    # print(data['Open'][-1])
    ma50Txt = ""
    ma200Txt = ""

    if data['Open'][-1] > data['MA50'][-1]:
        ma50Txt = "MA50 支撑线: " + str(round(data['MA50'][-1],2))
    elif data['Open'][-1] < data['MA50'][-1]:
        ma50Txt ="MA50 突破点: " + str(round(data['MA50'][-1],2))
    else :
        ma50Txt = "MA50 位于支撑线: " + str(round(data['MA50'][-1],2))

    if data['Open'][-1] > data['MA200'][-1]:
        ma200Txt = "MA200 支撑线: " + str(round(data['MA200'][-1],2))
    elif data['Open'][-1] < data['MA200'][-1]:
        ma200Txt ="MA200 突破点: " + str(round(data['MA200'][-1],2))
    else :
        ma200Txt = "MA200 位于支撑线: " + str(round(data['MA200'][-1],2))

    # plt.xlabel("股价: " + str(data['Open'][-1]), loc='left', fontproperties=fontP)
    # plt.xlabel(ma50Txt, loc='left', fontproperties=fontP)
    fig.text(.1, .08, "目前股价: " + str(round(data['Open'][-1],2)), ha='left', fontproperties=fontP)
    fig.text(.1, .05, ma50Txt, ha='left', fontproperties=fontP)
    fig.text(.1, .02, ma200Txt, ha='left', fontproperties=fontP)
    img = io.BytesIO()
    plt.savefig(img, format='png')
    img.seek(0)
    plot_url = base64.b64encode(img.getvalue()).decode()
    return render_template('plot.html', plot_url=plot_url, StockCodeList=list)
# plt.show()

list = []

class StockCode:
  def __init__(self, name, code):
    self.name = name
    self.code = code

# appending instances to list 
list.append( StockCode('7-ELEVEN MALAYSIA HOLDINGS BERHAD','5250.KL'))
list.append( StockCode('ABF MALAYSIA BOND INDEX FUND','0800EA.KL'))
list.append( StockCode('ABLEGROUP BERHAD','7086.KL'))
list.append( StockCode('ABM FUJIYA BERHAD','5198.KL'))
list.append( StockCode('ACE INNOVATE ASIA BERHAD','3028.KL'))
list.append( StockCode('ACME HOLDINGS BERHAD','7131.KL'))
list.append( StockCode('ACO GROUP BERHAD','218.KL'))
list.append( StockCode('ACOUSTECH BERHAD','7120.KL'))
list.append( StockCode('ADVANCE INFORMATION MARKETING BERHAD','122.KL'))
list.append( StockCode('ADVANCE SYNERGY BERHAD','1481.KL'))
list.append( StockCode('ADVANCECON HOLDINGS BERHAD','5281.KL'))
list.append( StockCode('ADVANCED PACKAGING TECHNOLOGY (M) BHD','9148.KL'))
list.append( StockCode('ADVENTA BERHAD','7191.KL'))
list.append( StockCode('AE MULTI HOLDINGS BERHAD','7146.KL'))
list.append( StockCode('AEMULUS HOLDINGS BERHAD','181.KL'))
list.append( StockCode('AEON CO. (M) BHD','6599.KL'))
list.append( StockCode('AEON CREDIT SERVICE (M) BERHAD','5139.KL'))
list.append( StockCode('AFFIN BANK BERHAD','5185.KL'))
list.append( StockCode('AGESON BERHAD','7145.KL'))
list.append( StockCode('AHB HOLDINGS BERHAD','7315.KL'))
list.append( StockCode('AHMAD ZAKI RESOURCES BERHAD','7078.KL'))
list.append( StockCode('AIRASIA GROUP BERHAD','5099.KL'))
list.append( StockCode('AIRASIA X BERHAD','5238.KL'))
list.append( StockCode('AJINOMOTO (MALAYSIA) BERHAD','2658.KL'))
list.append( StockCode('AJIYA BERHAD','7609.KL'))
list.append( StockCode('AL-`AQAR HEALTHCARE REIT','5116.KL'))
list.append( StockCode('ALAM MARITIM RESOURCES BERHAD','5115.KL'))
list.append( StockCode('ALCOM GROUP BERHAD','2674.KL'))
list.append( StockCode('ALLIANCE BANK MALAYSIA BERHAD','2488.KL'))
list.append( StockCode('ALLIANZ MALAYSIA BERHAD','1163.KL'))
list.append( StockCode('AL-SALAM REAL ESTATE INVESTMENT TRUST','5269.KL'))
list.append( StockCode('AMALGAMATED INDUSTRIAL STEEL BERHAD','2682.KL'))
list.append( StockCode('AMANAH HARTA TANAH PNB','4952.KL'))
list.append( StockCode('AMANAHRAYA REAL ESTATE INVESTMENT TRUST','5127.KL'))
list.append( StockCode('AMCORP PROPERTIES BERHAD','1007.KL'))
list.append( StockCode('AME ELITE CONSORTIUM BERHAD','5293.KL'))
list.append( StockCode('AMFIRST REAL ESTATE INVESTMENT TRUST','5120.KL'))
list.append( StockCode('AMLEX HOLDINGS BERHAD','3011.KL'))
list.append( StockCode('AMMB HOLDINGS BERHAD','1015.KL'))
list.append( StockCode('AMTEL HOLDINGS BERHAD','7031.KL'))
list.append( StockCode('AMVERTON BERHAD','5959.KL'))
list.append( StockCode('AMWAY (MALAYSIA) HOLDINGS BERHAD','6351.KL'))
list.append( StockCode('ANALABS RESOURCES BERHAD','7083.KL'))
list.append( StockCode('ANCOM BERHAD','4758.KL'))
list.append( StockCode('ANCOM LOGISTICS BERHAD','48.KL'))
list.append( StockCode('ANN JOO RESOURCES BERHAD','6556.KL'))
list.append( StockCode('ANZO HOLDINGS BERHAD','9342.KL'))
list.append( StockCode('APB RESOURCES BERHAD','5568.KL'))
list.append( StockCode('APEX EQUITY HOLDINGS BERHAD','5088.KL'))
list.append( StockCode('APEX HEALTHCARE BERHAD','7090.KL'))
list.append( StockCode('APFT BERHAD','5194.KL'))
list.append( StockCode('APM AUTOMOTIVE HOLDINGS BERHAD','5015.KL'))
list.append( StockCode('APOLLO FOOD HOLDINGS BERHAD','6432.KL'))
list.append( StockCode('APPASIA BERHAD','119.KL'))
list.append( StockCode('A-RANK BERHAD','7214.KL'))
list.append( StockCode('ARB BERHAD','7181.KL'))
list.append( StockCode('ARK RESOURCES HOLDINGS BERHAD','7007.KL'))
list.append( StockCode('ASDION BERHAD','68.KL'))
list.append( StockCode('ASIA BRANDS BERHAD','7722.KL'))
list.append( StockCode('ASIA FILE CORPORATION BHD','7129.KL'))
list.append( StockCode('ASIA MEDIA GROUP BERHAD','159.KL'))
list.append( StockCode('ASIA POLY HOLDINGS BERHAD','105.KL'))
list.append( StockCode('ASIAN PAC HOLDINGS BERHAD','4057.KL'))
list.append( StockCode('ASTINO BERHAD','7162.KL'))
list.append( StockCode('ASTRAL ASIA BERHAD','7054.KL'))
list.append( StockCode('ASTRAMINA GROUP BERHAD','3032.KL'))
list.append( StockCode('ASTRO MALAYSIA HOLDINGS BERHAD','6399.KL'))
list.append( StockCode('AT SYSTEMATIZATION BERHAD','72.KL'))
list.append( StockCode('ATA IMS BERHAD','8176.KL'))
list.append( StockCode('ATLAN HOLDINGS BHD','7048.KL'))
list.append( StockCode('ATRIUM REAL ESTATE INVESTMENT TRUST','5130.KL'))
list.append( StockCode('ATTA GLOBAL GROUP BERHAD','7099.KL'))
list.append( StockCode('AVILLION BERHAD','8885.KL'))
list.append( StockCode('AWC BERHAD','7579.KL'))
list.append( StockCode('AXIATA GROUP BERHAD','6888.KL'))
list.append( StockCode('AXIS REAL ESTATE INVESTMENT TRUST','5106.KL'))
list.append( StockCode('AYER HOLDINGS BERHAD','2305.KL'))
list.append( StockCode('AYS VENTURES BERHAD','5021.KL'))
list.append( StockCode('B.I.G. INDUSTRIES BERHAD','7005.KL'))
# list.append( StockCode('BABA ECO GROUP BERHAD','3012.KL'))
list.append( StockCode('BAHVEST RESOURCES BERHAD','98.KL'))
list.append( StockCode('BARAKAH OFFSHORE PETROLEUM BERHAD','7251.KL'))
list.append( StockCode('BATU KAWAN BERHAD','1899.KL'))
list.append( StockCode('BCB BERHAD','6602.KL'))
list.append( StockCode('BCM ALLIANCE BERHAD','187.KL'))
list.append( StockCode('BENALEC HOLDINGS BERHAD','5190.KL'))
list.append( StockCode('BERJAYA ASSETS BERHAD','3239.KL'))
list.append( StockCode('BERJAYA CORPORATION BERHAD','3395.KL'))
list.append( StockCode('BERJAYA FOOD BERHAD','5196.KL'))
list.append( StockCode('BERJAYA LAND BERHAD','4219.KL'))
list.append( StockCode('BERJAYA MEDIA BERHAD','6025.KL'))
list.append( StockCode('BERJAYA SPORTS TOTO BERHAD','1562.KL'))
list.append( StockCode('BERMAZ AUTO BERHAD','5248.KL'))
list.append( StockCode('BERTAM ALLIANCE BERHAD','9814.KL'))
list.append( StockCode('BIMB HOLDINGS BERHAD','5258.KL'))
list.append( StockCode('BINA DARULAMAN BERHAD','6173.KL'))
list.append( StockCode('BINA PURI HOLDINGS BHD','5932.KL'))
list.append( StockCode('BINASAT COMMUNICATIONS BERHAD','195.KL'))
list.append( StockCode('BINTAI KINDEN CORPORATION BERHAD','6998.KL'))
list.append( StockCode('BINTULU PORT HOLDINGS BERHAD','5032.KL'))
list.append( StockCode('BIOALPHA HOLDINGS BERHAD','179.KL'))
list.append( StockCode('BLD PLANTATION BHD.','5069.KL'))
list.append( StockCode('BOILERMECH HOLDINGS BERHAD','168.KL'))
list.append( StockCode('BONIA CORPORATION BERHAD','9288.KL'))
list.append( StockCode('BORNEO OIL BERHAD','7036.KL'))
list.append( StockCode('BOUSTEAD HEAVY INDUSTRIES CORPORATION BHD','8133.KL'))
list.append( StockCode('BOUSTEAD HOLDINGS BERHAD','2771.KL'))
list.append( StockCode('BOUSTEAD PLANTATIONS BERHAD','5254.KL'))
list.append( StockCode('BOX-PAK (MALAYSIA) BERHAD','6297.KL'))
list.append( StockCode('BP PLASTICS HOLDING BHD','5100.KL'))
list.append( StockCode('BRAHIM HOLDINGS BERHAD','9474.KL'))
list.append( StockCode('BREM HOLDING BERHAD','8761.KL'))
list.append( StockCode('BRIGHT PACKAGING INDUSTRY BERHAD','9938.KL'))
list.append( StockCode('BRITE-TECH BERHAD','11.KL'))
list.append( StockCode('BRITISH AMERICAN TOBACCO (MALAYSIA) BERHAD','4162.KL'))
list.append( StockCode('BSL CORPORATION BERHAD','7221.KL'))
list.append( StockCode('BTM RESOURCES BERHAD','7188.KL'))
list.append( StockCode('BUMI ARMADA BERHAD','5210.KL'))
list.append( StockCode('BURSA MALAYSIA BERHAD','1818.KL'))
list.append( StockCode('C.I. HOLDINGS BERHAD','2828.KL'))
list.append( StockCode('CAB CAKARAN CORPORATION BERHAD','7174.KL'))
list.append( StockCode('CABNET HOLDINGS BERHAD','191.KL'))
list.append( StockCode('CAELY HOLDINGS BHD','7154.KL'))
list.append( StockCode('CAHYA MATA SARAWAK BERHAD','2852.KL'))
list.append( StockCode('CAM RESOURCES BERHAD','7128.KL'))
list.append( StockCode('CAN-ONE BERHAD','5105.KL'))
list.append( StockCode('CAPITALAND MALAYSIA MALL TRUST','5180.KL'))
list.append( StockCode('CAREPLUS GROUP BERHAD','163.KL'))
list.append( StockCode('CARIMIN PETROLEUM BERHAD','5257.KL'))
list.append( StockCode('CARING PHARMACY GROUP BERHAD','5245.KL'))
list.append( StockCode('CARLSBERG BREWERY MALAYSIA BERHAD','2836.KL'))
list.append( StockCode('CB INDUSTRIAL PRODUCT HOLDING BERHAD','7076.KL'))
list.append( StockCode('CCK CONSOLIDATED HOLDINGS BERHAD','7035.KL'))
list.append( StockCode('CE TECHNOLOGY BERHAD','3024.KL'))
list.append( StockCode('CENSOF HOLDINGS BERHAD','5195.KL'))
list.append( StockCode('CENTRAL GLOBAL BERHAD','8052.KL'))
list.append( StockCode('CEPATWAWASAN GROUP BERHAD','8982.KL'))
list.append( StockCode('CHEETAH HOLDINGS BERHAD','7209.KL'))
list.append( StockCode('CHEMICAL COMPANY OF MALAYSIA BERHAD','2879.KL'))
list.append( StockCode('CHIN HIN GROUP BERHAD','5273.KL'))
list.append( StockCode('CHIN HIN GROUP PROPERTY BERHAD','7187.KL'))
list.append( StockCode('CHIN TECK PLANTATIONS BERHAD','1929.KL'))
list.append( StockCode('CHIN WELL HOLDINGS BERHAD','5007.KL'))
list.append( StockCode('CHINA AUTOMOBILE PARTS HOLDINGS LIMITED','5229.KL'))
list.append( StockCode('CHINA OUHUA WINERY HOLDINGS LIMITED','5188.KL'))
list.append( StockCode('CHOO BEE METAL INDUSTRIES BHD','5797.KL'))
list.append( StockCode('CHUAN HUAT RESOURCES BHD','7016.KL'))
list.append( StockCode('CIMB GROUP HOLDINGS BERHAD','1023.KL'))
list.append( StockCode('CJ CENTURY LOGISTICS HOLDINGS BERHAD','7117.KL'))
list.append( StockCode('CLASSIC SCENIC BERHAD','7202.KL'))
list.append( StockCode('CLOUDARON GROUP BERHAD','3001.KL'))
list.append( StockCode('CME GROUP BERHAD','7018.KL'))
list.append( StockCode('CN ASIA CORPORATION BHD','7986.KL'))
list.append( StockCode('CNI HOLDINGS BERHAD','5104.KL'))
list.append( StockCode('COASTAL CONTRACTS BHD','5071.KL'))
list.append( StockCode('COCOALAND HOLDINGS BERHAD','7205.KL'))
list.append( StockCode('COMFORT GLOVES BERHAD','2127.KL'))
list.append( StockCode('COMINTEL CORPORATION BHD','7195.KL'))
list.append( StockCode('COMPLETE LOGISTIC SERVICES BERHAD','5136.KL'))
list.append( StockCode('COMPUGATES HOLDINGS BERHAD','5037.KL'))
list.append( StockCode('COMPUTER FORMS (MALAYSIA) BERHAD','8044.KL'))
list.append( StockCode('CONCRETE ENGINEERING PRODUCTS BERHAD','8435.KL'))
list.append( StockCode('CONNECTCOUNTY HOLDINGS BERHAD','102.KL'))
list.append( StockCode('COSMOS TECHNOLOGY INTERNATIONAL BERHAD','3035.KL'))
list.append( StockCode('COUNTRY HEIGHTS HOLDINGS BHD','5738.KL'))
list.append( StockCode('COUNTRY VIEW BERHAD','5049.KL'))
list.append( StockCode('CRESCENDO CORPORATION BERHAD','6718.KL'))
list.append( StockCode('CREST BUILDER HOLDINGS BERHAD','8591.KL'))
list.append( StockCode('CRG INCORPORATED BERHAD','3016.KL'))
list.append( StockCode('CSC STEEL HOLDINGS BERHAD','5094.KL'))
list.append( StockCode('CUSCAPI BERHAD','51.KL'))
list.append( StockCode('CWG HOLDINGS BERHAD','9423.KL'))
list.append( StockCode('CYCLE & CARRIAGE BINTANG BERHAD','2925.KL'))
list.append( StockCode('CYL CORPORATION BERHAD','7157.KL'))
list.append( StockCode('CYMAO HOLDINGS BERHAD','5082.KL'))
list.append( StockCode('CYPARK RESOURCES BERHAD','5184.KL'))
list.append( StockCode('D&O GREEN TECHNOLOGIES BERHAD','7204.KL'))
list.append( StockCode('D.B.E. GURNEY RESOURCES BERHAD','7179.KL'))
list.append( StockCode('DAGANG NEXCHANGE BERHAD','4456.KL'))
list.append( StockCode('DAIBOCHI BERHAD','8125.KL'))
list.append( StockCode('DAMANSARA REALTY BHD','3484.KL'))
list.append( StockCode('DANAINFRA NASIONAL BERHAD','0400GA.KL'))
list.append( StockCode('DANAINFRA NASIONAL BERHAD','0400GB.KL'))
list.append( StockCode('DANAINFRA NASIONAL BERHAD','0400GC.KL'))
list.append( StockCode('DANCOMECH HOLDINGS BERHAD','5276.KL'))
list.append( StockCode('DATAPREP HOLDINGS BHD','8338.KL'))
list.append( StockCode('DATASONIC GROUP BERHAD','5216.KL'))
list.append( StockCode('DAYA MATERIALS BERHAD','91.KL'))
list.append( StockCode('DAYANG ENTERPRISE HOLDINGS BERHAD','5141.KL'))
list.append( StockCode('DEGEM BERHAD','7119.KL'))
list.append( StockCode('DELEUM BERHAD','5132.KL'))
list.append( StockCode('DESTINI BERHAD','7212.KL'))
list.append( StockCode('DGB ASIA BERHAD','152.KL'))
list.append( StockCode('DIALOG GROUP BERHAD','7277.KL'))
list.append( StockCode('DIGI.COM BERHAD','6947.KL'))
list.append( StockCode('DIGISTAR CORPORATION BERHAD','29.KL'))
list.append( StockCode('DIVERSIFIED GATEWAY SOLUTIONS BERHAD','131.KL'))
list.append( StockCode('DKLS INDUSTRIES BHD','7528.KL'))
list.append( StockCode('DKSH HOLDINGS (MALAYSIA) BERHAD','5908.KL'))
list.append( StockCode('D\'NONCE TECHNOLOGY BHD','7114.KL'))
list.append( StockCode('DOLOMITE CORPORATION BERHAD','5835.KL'))
list.append( StockCode('DOLPHIN INTERNATIONAL BERHAD','5265.KL'))
list.append( StockCode('DOMINANT ENTERPRISE BERHAD','7169.KL'))
list.append( StockCode('DPI HOLDINGS BERHAD','205.KL'))
list.append( StockCode('DPS RESOURCES BERHAD','7198.KL'))
list.append( StockCode('DRB-HICOM BERHAD','1619.KL'))
list.append( StockCode('DUFU TECHNOLOGY CORP. BERHAD','7233.KL'))
list.append( StockCode('DUOPHARMA BIOTECH BERHAD','7148.KL'))
list.append( StockCode('DUTALAND BERHAD','3948.KL'))
list.append( StockCode('DUTCH LADY MILK INDUSTRIES BERHAD','3026.KL'))
list.append( StockCode('DWL RESOURCES BERHAD','7165.KL'))
list.append( StockCode('DYNACIATE GROUP BERHAD','5178.KL'))
list.append( StockCode('E.A.TECHNIQUE (M) BERHAD','5259.KL'))
list.append( StockCode('EA HOLDINGS BERHAD','154.KL'))
list.append( StockCode('EASTERN & ORIENTAL BERHAD','3417.KL'))
list.append( StockCode('EASTLAND EQUITY BHD','2097.KL'))
list.append( StockCode('ECM LIBRA GROUP BERHAD','2143.KL'))
list.append( StockCode('ECO WORLD DEVELOPMENT GROUP BERHAD','8206.KL'))
list.append( StockCode('ECO WORLD INTERNATIONAL BERHAD','5283.KL'))
list.append( StockCode('ECOBUILT HOLDINGS BERHAD','59.KL'))
list.append( StockCode('ECOFIRST CONSOLIDATED BHD','3557.KL'))
list.append( StockCode('ECONPILE HOLDINGS BERHAD','5253.KL'))
list.append( StockCode('EDARAN BERHAD','5036.KL'))
list.append( StockCode('EDEN INC. BERHAD','7471.KL'))
list.append( StockCode('EDUSPEC HOLDINGS BERHAD','107.KL'))
list.append( StockCode('EFFICIENT E-SOLUTIONS BERHAD','64.KL'))
list.append( StockCode('EG INDUSTRIES BERHAD','8907.KL'))
list.append( StockCode('EITA RESOURCES BERHAD','5208.KL'))
list.append( StockCode('EKA NOODLES BERHAD','7182.KL'))
list.append( StockCode('EKOVEST BERHAD','8877.KL'))
list.append( StockCode('EKSONS CORPORATION BERHAD','9016.KL'))
list.append( StockCode('ELK-DESA RESOURCES BERHAD','5228.KL'))
list.append( StockCode('ELSOFT RESEARCH BERHAD','90.KL'))
list.append( StockCode('EMICO HOLDINGS BERHAD','9091.KL'))
list.append( StockCode('ENCORP BERHAD','6076.KL'))
list.append( StockCode('ENEST GROUP BERHAD','3025.KL'))
list.append( StockCode('ENG KAH CORPORATION BERHAD','7149.KL'))
list.append( StockCode('ENGTEX GROUP BERHAD','5056.KL'))
list.append( StockCode('ENRA GROUP BERHAD','8613.KL'))
list.append( StockCode('EONMETALL GROUP BERHAD','7217.KL'))
list.append( StockCode('EP MANUFACTURING BHD','7773.KL'))
list.append( StockCode('EQUITIESTRACKER HOLDINGS BERHAD','3021.KL'))
list.append( StockCode('ES CERAMICS TECHNOLOGY BHD','100.KL'))
list.append( StockCode('ESTHETICS INTERNATIONAL GROUP BERHAD','5081.KL'))
list.append( StockCode('EUPE CORPORATION BERHAD','6815.KL'))
list.append( StockCode('EURO HOLDINGS BERHAD','7208.KL'))
list.append( StockCode('EUROSPAN HOLDINGS BERHAD','7094.KL'))
list.append( StockCode('EVERGREEN FIBREBOARD BERHAD','5101.KL'))
list.append( StockCode('EVERSAFE RUBBER BERHAD','190.KL'))
list.append( StockCode('EVERSENDAI CORPORATION BERHAD','5205.KL'))
list.append( StockCode('EWEIN BERHAD','7249.KL'))
list.append( StockCode('EXCEL FORCE MSC BERHAD','65.KL'))
list.append( StockCode('FACB INDUSTRIES INCORPORATED BERHAD','2984.KL'))
list.append( StockCode('FAJARBARU BUILDER GROUP BHD','7047.KL'))
list.append( StockCode('FAR EAST HOLDINGS BERHAD','5029.KL'))
list.append( StockCode('FARLIM GROUP (MALAYSIA) BHD','6041.KL'))
list.append( StockCode('FAVELLE FAVCO BERHAD','7229.KL'))
list.append( StockCode('FCW HOLDINGS BERHAD','2755.KL'))
list.append( StockCode('FEDERAL INTERNATIONAL HOLDINGS BERHAD','8605.KL'))
list.append( StockCode('FGV HOLDINGS BERHAD','5222.KL'))
list.append( StockCode('FIAMMA HOLDINGS BERHAD','6939.KL'))
list.append( StockCode('FIBON BERHAD','149.KL'))
list.append( StockCode('FIBROMAT (M) BERHAD','3026.KL'))
list.append( StockCode('FIMA CORPORATION BERHAD','3107.KL'))
list.append( StockCode('FINTEC GLOBAL BERHAD','150.KL'))
list.append( StockCode('FITTERS DIVERSIFIED BERHAD','9318.KL'))
list.append( StockCode('FOCUS DYNAMICS GROUP BERHAD','116.KL'))
list.append( StockCode('FOCUS LUMBER BERHAD','5197.KL'))
list.append( StockCode('FOCUS POINT HOLDINGS BERHAD','157.KL'))
list.append( StockCode('FORMOSA PROSONIC INDUSTRIES BERHAD','9172.KL'))
list.append( StockCode('FOUNDPAC GROUP BERHAD','5277.KL'))
list.append( StockCode('FRASER & NEAVE HOLDINGS BHD','3689.KL'))
list.append( StockCode('FREIGHT MANAGEMENT HOLDINGS BERHAD','7210.KL'))
list.append( StockCode('FRONTKEN CORPORATION BERHAD','128.KL'))
list.append( StockCode('FSBM HOLDINGS BERHAD','9377.KL'))
list.append( StockCode('FTSE BURSA MALAYSIA KLCI ETF','0820EA.KL'))
list.append( StockCode('G NEPTUNE BERHAD','45.KL'))
list.append( StockCode('G3 GLOBAL BERHAD','7184.KL'))
list.append( StockCode('GABUNGAN AQRS BERHAD','5226.KL'))
list.append( StockCode('GADANG HOLDINGS BHD','9261.KL'))
list.append( StockCode('GAGASAN NADI CERGAS BERHAD','206.KL'))
list.append( StockCode('GAMUDA BERHAD','5398.KL'))
list.append( StockCode('GAS MALAYSIA BERHAD','5209.KL'))
list.append( StockCode('GD EXPRESS CARRIER BERHAD','78.KL'))
list.append( StockCode('GDB HOLDINGS BERHAD','198.KL'))
list.append( StockCode('GENETEC TECHNOLOGY BERHAD','104.KL'))
list.append( StockCode('GENTING BERHAD','3182.KL'))
list.append( StockCode('GENTING MALAYSIA BERHAD','4715.KL'))
list.append( StockCode('GENTING PLANTATIONS BERHAD','2291.KL'))
list.append( StockCode('GEORGE KENT (MALAYSIA) BERHAD','3204.KL'))
list.append( StockCode('GE-SHEN CORPORATION BERHAD','7197.KL'))
list.append( StockCode('GETS GLOBAL BERHAD','5079.KL'))
list.append( StockCode('GFM SERVICES BERHAD','39.KL'))
list.append( StockCode('GHL SYSTEMS BERHAD','21.KL'))
list.append( StockCode('GLOBAL ORIENTAL BERHAD','1147.KL'))
list.append( StockCode('GLOBALTEC FORMATION BERHAD','5220.KL'))
list.append( StockCode('GLOBETRONICS TECHNOLOGY BERHAD','7022.KL'))
list.append( StockCode('GLOMAC BERHAD','5020.KL'))
list.append( StockCode('GOLDEN LAND BERHAD','7382.KL'))
list.append( StockCode('GOLDEN PHAROS BERHAD','5649.KL'))
list.append( StockCode('GOODWAY INTEGRATED INDUSTRIES BERHAD','7192.KL'))
list.append( StockCode('GOPENG BERHAD','2135.KL'))
list.append( StockCode('GPA HOLDINGS BERHAD','7096.KL'))
list.append( StockCode('GPP RESOURCES BERHAD','3029.KL'))
list.append( StockCode('GRAND CENTRAL ENTERPRISES BHD','5592.KL'))
list.append( StockCode('GRAND HOOVER BERHAD','7010.KL'))
list.append( StockCode('GRAND-FLO BERHAD','56.KL'))
list.append( StockCode('GREATECH TECHNOLOGY BERHAD','208.KL'))
list.append( StockCode('GREEN OCEAN CORPORATION BERHAD','74.KL'))
list.append( StockCode('GREEN PACKET BERHAD','82.KL'))
list.append( StockCode('GREENYIELD BERHAD','136.KL'))
list.append( StockCode('GROMUTUAL BERHAD','9962.KL'))
list.append( StockCode('GUAN CHONG BERHAD','5102.KL'))
list.append( StockCode('GUH HOLDINGS BERHAD','3247.KL'))
list.append( StockCode('GUNUNG CAPITAL BERHAD','7676.KL'))
list.append( StockCode('GUOCOLAND (MALAYSIA) BERHAD','1503.KL'))
list.append( StockCode('HAI-O ENTERPRISE BERHAD','7668.KL'))
list.append( StockCode('HANDAL ENERGY BERHAD','7253.KL'))
list.append( StockCode('HAP SENG CONSOLIDATED BERHAD','3034.KL'))
list.append( StockCode('HAP SENG PLANTATIONS HOLDINGS BERHAD','5138.KL'))
list.append( StockCode('HARBOUR-LINK GROUP BERHAD','2062.KL'))
list.append( StockCode('HARN LEN CORPORATION BHD','7501.KL'))
list.append( StockCode('HARRISONS HOLDINGS (MALAYSIA) BERHAD','5008.KL'))
list.append( StockCode('HARTALEGA HOLDINGS BERHAD','5168.KL'))
list.append( StockCode('HB GLOBAL LIMITED','5187.KL'))
list.append( StockCode('HCK CAPITAL GROUP BERHAD','7105.KL'))
list.append( StockCode('HEINEKEN MALAYSIA BERHAD','3255.KL'))
list.append( StockCode('HEITECH PADU BERHAD','5028.KL'))
list.append( StockCode('HEKTAR REAL ESTATE INVESTMENT TRUST','5121.KL'))
list.append( StockCode('HENG HUAT RESOURCES GROUP BERHAD','175.KL'))
list.append( StockCode('HENGYUAN REFINING COMPANY BERHAD','4324.KL'))
list.append( StockCode('HEVEABOARD BERHAD','5095.KL'))
list.append( StockCode('HEXTAR GLOBAL BERHAD','5151.KL'))
list.append( StockCode('HEXZA CORPORATION BERHAD','3298.KL'))
list.append( StockCode('HIAP HUAT HOLDINGS BERHAD','160.KL'))
list.append( StockCode('HIAP TECK VENTURE BERHAD','5072.KL'))
list.append( StockCode('HIBISCUS PETROLEUM BERHAD','5199.KL'))
list.append( StockCode('HIL INDUSTRIES BERHAD','8443.KL'))
list.append( StockCode('HLT GLOBAL BERHAD','188.KL'))
list.append( StockCode('HO HUP CONSTRUCTION COMPANY BHD','5169.KL'))
list.append( StockCode('HO WAH GENTING BERHAD','9601.KL'))
list.append( StockCode('HOCK HENG STONE INDUSTRIES BHD','5165.KL'))
list.append( StockCode('HOCK SENG LEE BERHAD','6238.KL'))
list.append( StockCode('HOMERITZ CORPORATION BERHAD','5160.KL'))
list.append( StockCode('HONG LEONG BANK BERHAD','5819.KL'))
list.append( StockCode('HONG LEONG CAPITAL BERHAD','5274.KL'))
list.append( StockCode('HONG LEONG FINANCIAL GROUP BERHAD','1082.KL'))
list.append( StockCode('HONG LEONG INDUSTRIES BERHAD','3301.KL'))
list.append( StockCode('HPMT HOLDINGS BERHAD','5291.KL'))
list.append( StockCode('HSS ENGINEERS BERHAD','185.KL'))
list.append( StockCode('HUA YANG BERHAD','5062.KL'))
list.append( StockCode('HUBLINE BERHAD','7013.KL'))
list.append( StockCode('HUME INDUSTRIES BERHAD','5000.KL'))
list.append( StockCode('HUP SENG INDUSTRIES BERHAD','5024.KL'))
list.append( StockCode('HWA TAI INDUSTRIES BERHAD','8478.KL'))
list.append( StockCode('I-BERHAD','4251.KL'))
list.append( StockCode('IBRACO BERHAD','5084.KL'))
list.append( StockCode('ICAPITAL.BIZ BERHAD','5108.KL'))
list.append( StockCode('ICON OFFSHORE BERHAD','5255.KL'))
list.append( StockCode('ICONIC WORLDWIDE BERHAD','9113.KL'))
list.append( StockCode('IDB TECHNOLOGIES BERHAD','3030.KL'))
list.append( StockCode('IDEAL UNITED BINTANG INTERNATIONAL BERHAD','9687.KL'))
list.append( StockCode('IDIMENSION CONSOLIDATED BHD','174.KL'))
list.append( StockCode('IFCA MSC BERHAD','23.KL'))
list.append( StockCode('IGB BERHAD','5606.KL'))
list.append( StockCode('IGB REAL ESTATE INVESTMENT TRUST','5227.KL'))
list.append( StockCode('IHH HEALTHCARE BERHAD','5225.KL'))
list.append( StockCode('IHSAN SUKUK-ETBS 4.60%0824','0401GA.KL'))
list.append( StockCode('IJM CORPORATION BERHAD','3336.KL'))
list.append( StockCode('IJM PLANTATIONS BERHAD','2216.KL'))
list.append( StockCode('IKHMAS JAYA GROUP BERHAD','5268.KL'))
list.append( StockCode('IMASPRO CORPORATION BERHAD','7222.KL'))
list.append( StockCode('IMPIANA HOTELS BERHAD','7243.KL'))
list.append( StockCode('INARI AMERTRON BERHAD','166.KL'))
list.append( StockCode('INCH KENNETH KAJANG RUBBER PUBLIC LTD CO','2607.KL'))
list.append( StockCode('INDUSTRONICS BERHAD','9393.KL'))
list.append( StockCode('INIX TECHNOLOGIES HOLDINGS BERHAD','94.KL'))
list.append( StockCode('INNATURE BERHAD','5295.KL'))
list.append( StockCode('INNITY CORPORATION BERHAD','147.KL'))
list.append( StockCode('INNOPRISE PLANTATIONS BERHAD','6262.KL'))
list.append( StockCode('INSAS BERHAD','3379.KL'))
list.append( StockCode('INTA BINA GROUP BERHAD','192.KL'))
list.append( StockCode('INTEGRATED LOGISTICS BHD','5614.KL'))
list.append( StockCode('IOI CORPORATION BERHAD','1961.KL'))
list.append( StockCode('IOI PROPERTIES GROUP BERHAD','5249.KL'))
list.append( StockCode('IPMUDA BERHAD','5673.KL'))
list.append( StockCode('IQ GROUP HOLDINGS BERHAD','5107.KL'))
list.append( StockCode('IQZAN HOLDING BERHAD','7183.KL'))
list.append( StockCode('IREKA CORPORATION BERHAD','8834.KL'))
list.append( StockCode('IRIS CORPORATION BERHAD','10.KL'))
list.append( StockCode('ISKANDAR WATERFRONT CITY BERHAD','1589.KL'))
list.append( StockCode('I-STONE GROUP BERHAD','209.KL'))
list.append( StockCode('IVORY PROPERTIES GROUP BERHAD','5175.KL'))
list.append( StockCode('JADE MARVEL GROUP BERHAD','7043.KL'))
list.append( StockCode('JADI IMAGING HOLDINGS BERHAD','7223.KL'))
list.append( StockCode('JAG BERHAD','24.KL'))
list.append( StockCode('JAKS RESOURCES BERHAD','4723.KL'))
list.append( StockCode('JASA KITA BERHAD','8648.KL'))
list.append( StockCode('JAYA TIASA HOLDINGS BHD','4383.KL'))
list.append( StockCode('JAYCORP BERHAD','7152.KL'))
list.append( StockCode('JCBNEXT BERHAD','58.KL'))
list.append( StockCode('JCY INTERNATIONAL BERHAD','5161.KL'))
list.append( StockCode('JERASIA CAPITAL BERHAD','8931.KL'))
list.append( StockCode('JF TECHNOLOGY BERHAD','146.KL'))
list.append( StockCode('JHM CONSOLIDATION BERHAD','127.KL'))
list.append( StockCode('JIANKUN INTERNATIONAL BERHAD','8923.KL'))
list.append( StockCode('JKG LAND BERHAD','6769.KL'))
list.append( StockCode('JM EDUCATION GROUP BERHAD','3003.KL'))
list.append( StockCode('JOHAN HOLDINGS BERHAD','3441.KL'))
list.append( StockCode('JOHORE TIN BERHAD','7167.KL'))
list.append( StockCode('K.SENG SENG CORPORATION BERHAD','5192.KL'))
list.append( StockCode('KAMDAR GROUP (M) BERHAD','8672.KL'))
list.append( StockCode('KANGER INTERNATIONAL BERHAD','170.KL'))
list.append( StockCode('KAREX BERHAD','5247.KL'))
list.append( StockCode('KARYON INDUSTRIES BERHAD','54.KL'))
list.append( StockCode('KAWAN FOOD BERHAD','7216.KL'))
list.append( StockCode('KECK SENG (MALAYSIA) BERHAD','3476.KL'))
list.append( StockCode('KEIN HING INTERNATIONAL BERHAD','7199.KL'))
list.append( StockCode('KEJURUTERAAN ASASTERA BERHAD','193.KL'))
list.append( StockCode('KELINGTON GROUP BERHAD','151.KL'))
list.append( StockCode('KEN HOLDINGS BERHAD','7323.KL'))
list.append( StockCode('KENANGA INVESTMENT BANK BERHAD','6483.KL'))
list.append( StockCode('KENANGA KLCI DAILY (-1X) INVERSE ETF','0835EA.KL'))
list.append( StockCode('KENANGA KLCI DAILY 2X LEVERAGED ETF','0834EA.KL'))
list.append( StockCode('KERJAYA PROSPEK GROUP BERHAD','7161.KL'))
list.append( StockCode('KERJAYA PROSPEK PROPERTY BERHAD','7077.KL'))
list.append( StockCode('KESM INDUSTRIES BERHAD','9334.KL'))
list.append( StockCode('KEY ALLIANCE GROUP BERHAD','36.KL'))
list.append( StockCode('KEY ASIC BERHAD','143.KL'))
list.append( StockCode('KHEE SAN BERHAD','6203.KL'))
list.append( StockCode('KHIND HOLDINGS BERHAD','7062.KL'))
list.append( StockCode('KIA LIM BERHAD','6211.KL'))
list.append( StockCode('KIM HIN INDUSTRY BERHAD','5371.KL'))
list.append( StockCode('KIM HIN JOO (MALAYSIA) BERHAD','210.KL'))
list.append( StockCode('KIM LOONG RESOURCES BERHAD','5027.KL'))
list.append( StockCode('KIM TECK CHEONG CONSOLIDATED BERHAD','180.KL'))
list.append( StockCode('KIMLUN CORPORATION BERHAD','5171.KL'))
list.append( StockCode('KINSTEEL BHD','5060.KL'))
list.append( StockCode('KIP REAL ESTATE INVESTMENT TRUST','5280.KL'))
list.append( StockCode('KKB ENGINEERING BERHAD','9466.KL'))
list.append( StockCode('KLCC PROPERTY HOLDINGS BERHAD','5235SS.KL'))
list.append( StockCode('KLCC REAL ESTATE INVESTMENT TRUST','5235SS.KL'))
list.append( StockCode('KLUANG RUBBER COMPANY (MALAYA) BERHAD','2453.KL'))
list.append( StockCode('KNM GROUP BERHAD','7164.KL'))
list.append( StockCode('KNUSFORD BERHAD','5035.KL'))
list.append( StockCode('KOBAY TECHNOLOGY BERHAD','6971.KL'))
list.append( StockCode('KOMARKCORP BERHAD','7017.KL'))
list.append( StockCode('K-ONE TECHNOLOGY BERHAD','111.KL'))
list.append( StockCode('KONSORTIUM TRANSNASIONAL BERHAD','4847.KL'))
list.append( StockCode('KOSSAN RUBBER INDUSTRIES BERHAD','7153.KL'))
list.append( StockCode('KOTRA INDUSTRIES BERHAD','2.KL'))
list.append( StockCode('KPJ HEALTHCARE BERHAD','5878.KL'))
list.append( StockCode('KPS CONSORTIUM BERHAD','9121.KL'))
list.append( StockCode('KRETAM HOLDINGS BERHAD','1996.KL'))
list.append( StockCode('KRONOLOGI ASIA BERHAD','176.KL'))
list.append( StockCode('KSL HOLDINGS BERHAD','5038.KL'))
list.append( StockCode('K-STAR SPORTS LIMITED','5172.KL'))
list.append( StockCode('KUALA LUMPUR KEPONG BERHAD','2445.KL'))
list.append( StockCode('KUB MALAYSIA BERHAD','6874.KL'))
list.append( StockCode('KUCHAI DEVELOPMENT BERHAD','2186.KL'))
list.append( StockCode('KUMPULAN FIMA BERHAD','6491.KL'))
list.append( StockCode('KUMPULAN H & L HIGH-TECH BERHAD','7033.KL'))
list.append( StockCode('KUMPULAN JETSON BERHAD','9083.KL'))
list.append( StockCode('KUMPULAN PERANGSANG SELANGOR BERHAD','5843.KL'))
list.append( StockCode('KUMPULAN POWERNET BERHAD','7130.KL'))
list.append( StockCode('KWANTAS CORPORATION BERHAD','6572.KL'))
list.append( StockCode('KYM HOLDINGS BERHAD','8362.KL'))
list.append( StockCode('LAMBO GROUP BERHAD','18.KL'))
list.append( StockCode('LAND & GENERAL BERHAD','3174.KL'))
list.append( StockCode('LANDMARKS BERHAD','1643.KL'))
list.append( StockCode('LATITUDE TREE HOLDINGS BERHAD','7006.KL'))
list.append( StockCode('LAY HONG BERHAD','9385.KL'))
list.append( StockCode('LB ALUMINIUM BERHAD','9326.KL'))
list.append( StockCode('LBI CAPITAL BERHAD','8494.KL'))
list.append( StockCode('LBS BINA GROUP BERHAD','5789.KL'))
list.append( StockCode('LEADER STEEL HOLDINGS BERHAD','9881.KL'))
list.append( StockCode('LEBTECH BERHAD','9628.KL'))
list.append( StockCode('LEE SWEE KIAT GROUP BERHAD','8079.KL'))
list.append( StockCode('LEON FUAT BERHAD','5232.KL'))
list.append( StockCode('LEONG HUP INTERNATIONAL BERHAD','6633.KL'))
list.append( StockCode('LEWEKO RESOURCES BERHAD','8745.KL'))
list.append( StockCode('LFE CORPORATION BERHAD','7170.KL'))
list.append( StockCode('LIEN HOE CORPORATION BERHAD','3573.KL'))
list.append( StockCode('LII HEN INDUSTRIES BHD.','7089.KL'))
list.append( StockCode('LINGKARAN TRANS KOTA HOLDINGS BERHAD','6645.KL'))
list.append( StockCode('LION INDUSTRIES CORPORATION BERHAD','4235.KL'))
list.append( StockCode('LION POSIM BERHAD','8486.KL'))
list.append( StockCode('LKL INTERNATIONAL BERHAD','182.KL'))
list.append( StockCode('LONDON BISCUITS BERHAD','7126.KL'))
list.append( StockCode('LOTTE CHEMICAL TITAN HOLDING BERHAD','5284.KL'))
list.append( StockCode('LOTUS KFM BERHAD','8303.KL'))
list.append( StockCode('LPI CAPITAL BHD','8621.KL'))
list.append( StockCode('LTKM BERHAD','7085.KL'))
list.append( StockCode('LUSTER INDUSTRIES BHD.','5068.KL'))
list.append( StockCode('LUXCHEM CORPORATION BERHAD','5143.KL'))
list.append( StockCode('LYC HEALTHCARE BERHAD','75.KL'))
list.append( StockCode('LYSAGHT GALVANIZED STEEL BERHAD','9199.KL'))
list.append( StockCode('M N C WIRELESS BERHAD','103.KL'))
list.append( StockCode('M3 TECHNOLOGIES (ASIA) BERHAD','17.KL'))
list.append( StockCode('MAA GROUP BERHAD','1198.KL'))
list.append( StockCode('MACPIE BERHAD','140.KL'))
list.append( StockCode('MAGNA PRIMA BERHAD','7617.KL'))
list.append( StockCode('MAGNI-TECH INDUSTRIES BERHAD','7087.KL'))
list.append( StockCode('MAGNUM BERHAD','3859.KL'))
list.append( StockCode('MAH SING GROUP BERHAD','8583.KL'))
list.append( StockCode('MAJUPERAK HOLDINGS BERHAD','8141.KL'))
list.append( StockCode('MALAKOFF CORPORATION BERHAD','5264.KL'))
list.append( StockCode('MALAYAN BANKING BERHAD','1155.KL'))
list.append( StockCode('MALAYAN CEMENT BERHAD','3794.KL'))
list.append( StockCode('MALAYAN FLOUR MILLS BERHAD','3662.KL'))
list.append( StockCode('MALAYAN UNITED INDUSTRIES BERHAD','3891.KL'))
list.append( StockCode('MALAYSIA AIRPORTS HOLDINGS BERHAD','5014.KL'))
list.append( StockCode('MALAYSIA BUILDING SOCIETY BERHAD','1171.KL'))
list.append( StockCode('MALAYSIA MARINE AND HEAVY ENGINEERING HOLDINGS BERHAD','5186.KL'))
list.append( StockCode('MALAYSIA PACIFIC CORPORATION BERHAD','6548.KL'))
list.append( StockCode('MALAYSIA SMELTING CORPORATION BERHAD','5916.KL'))
list.append( StockCode('MALAYSIA STEEL WORKS (KL) BHD','5098.KL'))
list.append( StockCode('MALAYSIAN BULK CARRIERS BERHAD','5077.KL'))
list.append( StockCode('MALAYSIAN GENOMICS RESOURCE CENTRE BERHAD','155.KL'))
list.append( StockCode('MALAYSIAN PACIFIC INDUSTRIES BERHAD','3867.KL'))
list.append( StockCode('MALAYSIAN RESOURCES CORPORATION BERHAD','1651.KL'))
list.append( StockCode('MALPAC HOLDINGS BERHAD','4936.KL'))
list.append( StockCode('MALTON BERHAD','6181.KL'))
list.append( StockCode('MANAGEPAY SYSTEMS BERHAD','156.KL'))
list.append( StockCode('MANFORCE GROUP BERHAD','3015.KL'))
list.append( StockCode('MANULIFE HOLDINGS BERHAD','1058.KL'))
list.append( StockCode('MARCO HOLDINGS BERHAD','3514.KL'))
list.append( StockCode('MARINE & GENERAL BERHAD','5078.KL'))
list.append( StockCode('MASTER-PACK GROUP BERHAD','7029.KL'))
list.append( StockCode('MATANG BERHAD','189.KL'))
list.append( StockCode('MATRIX CONCEPTS HOLDINGS BERHAD','5236.KL'))
list.append( StockCode('MATRIX PARKING SOLUTION HOLDINGS BERHAD','3019.KL'))
list.append( StockCode('MAXIS BERHAD','6012.KL'))
list.append( StockCode('MB WORLD GROUP BERHAD','7189.KL'))
list.append( StockCode('MBM RESOURCES BHD','5983.KL'))
list.append( StockCode('MCE HOLDINGS BERHAD','7004.KL'))
list.append( StockCode('MCLEAN TECHNOLOGIES BERHAD','167.KL'))
list.append( StockCode('MCOM HOLDINGS BERHAD','3022.KL'))
list.append( StockCode('MCT BERHAD','5182.KL'))
list.append( StockCode('MEDIA CHINESE INTERNATIONAL LIMITED','5090.KL'))
list.append( StockCode('MEDIA PRIMA BERHAD','4502.KL'))
list.append( StockCode('MEGA FIRST CORPORATION BERHAD','3069.KL'))
list.append( StockCode('MEGA SUN CITY HOLDINGS BERHAD','81.KL'))
list.append( StockCode('MELATI EHSAN HOLDINGS BERHAD','5129.KL'))
list.append( StockCode('MELEWAR INDUSTRIAL GROUP BERHAD','3778.KL'))
list.append( StockCode('MENANG CORPORATION (M) BERHAD','1694.KL'))
list.append( StockCode('MENTIGA CORPORATION BERHAD','5223.KL'))
list.append( StockCode('MERCURY INDUSTRIES BERHAD','8192.KL'))
list.append( StockCode('MERIDIAN BERHAD','5040.KL'))
list.append( StockCode('MESB BERHAD','7234.KL'))
list.append( StockCode('MESINIAGA BERHAD','5011.KL'))
list.append( StockCode('MESTRON HOLDINGS BERHAD','207.KL'))
list.append( StockCode('MESTRON HOLDINGS BERHAD','207.KL'))
list.append( StockCode('METRO HEALTHCARE BERHAD','3005.KL'))
list.append( StockCode('METROD HOLDINGS BERHAD','6149.KL'))
list.append( StockCode('METRONIC GLOBAL BERHAD','43.KL'))
list.append( StockCode('MGB BERHAD','7595.KL'))
list.append( StockCode('MHC PLANTATIONS BHD','5026.KL'))
list.append( StockCode('MI TECHNOVATION BERHAD','5286.KL'))
list.append( StockCode('MICROLINK SOLUTIONS BERHAD','126.KL'))
list.append( StockCode('MIECO CHIPBOARD BERHAD','5001.KL'))
list.append( StockCode('MIKRO MSC BERHAD','112.KL'))
list.append( StockCode('MILUX CORPORATION BERHAD','7935.KL'))
list.append( StockCode('MINDA GLOBAL BERHAD','5166.KL'))
list.append( StockCode('MINETECH RESOURCES BERHAD','7219.KL'))
list.append( StockCode('MINHO (M) BERHAD','5576.KL'))
list.append( StockCode('MINTYE BERHAD','5886.KL'))
list.append( StockCode('MISC BERHAD','3816.KL'))
list.append( StockCode('MITRAJAYA HOLDINGS BERHAD','9571.KL'))
list.append( StockCode('MK LAND HOLDINGS BERHAD','8893.KL'))
list.append( StockCode('MKH BERHAD','6114.KL'))
list.append( StockCode('MLABS SYSTEMS BERHAD','85.KL'))
list.append( StockCode('MMAG HOLDINGS BERHAD','34.KL'))
list.append( StockCode('MMC CORPORATION BERHAD','2194.KL'))
list.append( StockCode('MMIS BERHAD','3027.KL'))
list.append( StockCode('MMS VENTURES BERHAD','113.KL'))
list.append( StockCode('MNRB HOLDINGS BERHAD','6459.KL'))
list.append( StockCode('MPHB CAPITAL BERHAD','5237.KL'))
list.append( StockCode('MQ TECHNOLOGY BERHAD','70.KL'))
list.append( StockCode('MRCB-QUILL REIT','5123.KL'))
list.append( StockCode('MSCM HOLDINGS BERHAD','41.KL'))
list.append( StockCode('MSM MALAYSIA HOLDINGS BERHAD','5202.KL'))
list.append( StockCode('MTAG GROUP BERHAD','213.KL'))
list.append( StockCode('MTD ACPI ENGINEERING BERHAD','5924.KL'))
list.append( StockCode('MTOUCHE TECHNOLOGY BERHAD','92.KL'))
list.append( StockCode('MUAR BAN LEE GROUP BERHAD','5152.KL'))
list.append( StockCode('MUDA HOLDINGS BERHAD','3883.KL'))
list.append( StockCode('MUDAJAYA GROUP BERHAD','5085.KL'))
list.append( StockCode('MUHIBBAH ENGINEERING (M) BHD','5703.KL'))
list.append( StockCode('MUI PROPERTIES BERHAD','3913.KL'))
list.append( StockCode('MULPHA INTERNATIONAL BERHAD','3905.KL'))
list.append( StockCode('MULTI-USAGE HOLDINGS BERHAD','9539.KL'))
list.append( StockCode('MY E.G. SERVICES BERHAD','138.KL'))
list.append( StockCode('MYCRON STEEL BERHAD','5087.KL'))
list.append( StockCode('MYETF DOW JONES ISLAMIC MARKET MALAYSIA TITANS 25','0821EA.KL'))
list.append( StockCode('MYETF DOW JONES U.S. TITANS 50','0827EA.KL'))
list.append( StockCode('MYETF MSCI MALAYSIA ISLAMIC DIVIDEND','0824EA.KL'))
list.append( StockCode('MYETF MSCI SEA ISLAMIC DIVIDEND','0825EA.KL'))
list.append( StockCode('MYETF THOMSON REUTERS ASIA PACIFIC ex-JAPAN ISLAMIC AGRIBUSINESS','0826EA.KL'))
list.append( StockCode('MYKRIS INTERNATIONAL BERHAD','3010.KL'))
list.append( StockCode('MYNEWS HOLDINGS BERHAD','5275.KL'))
list.append( StockCode('N2N CONNECT BERHAD','108.KL'))
list.append( StockCode('NAIM HOLDINGS BERHAD','5073.KL'))
list.append( StockCode('NATIONWIDE EXPRESS HOLDINGS BERHAD','9806.KL'))
list.append( StockCode('NEGRI SEMBILAN OIL PALMS BERHAD','2038.KL'))
list.append( StockCode('NESTLE (MALAYSIA) BERHAD','4707.KL'))
list.append( StockCode('NETX HOLDINGS BERHAD','20.KL'))
list.append( StockCode('NEW HOONG FATT HOLDINGS BERHAD','7060.KL'))
list.append( StockCode('NEXGRAM HOLDINGS BERHAD','96.KL'))
list.append( StockCode('NEXTGREEN GLOBAL BERHAD','7241.KL'))
list.append( StockCode('NI HSIN RESOURCES BERHAD','7215.KL'))
list.append( StockCode('NICHE CAPITAL EMAS HOLDINGS BERHAD','7139.KL'))
list.append( StockCode('NOTION VTEC BERHAD','83.KL'))
list.append( StockCode('NOVA MSC BERHAD','26.KL'))
list.append( StockCode('NOVA PHARMA SOLUTIONS BERHAD','3006.KL'))
list.append( StockCode('NOVA WELLNESS GROUP BERHAD','201.KL'))
list.append( StockCode('NPC RESOURCES BERHAD','5047.KL'))
list.append( StockCode('NTPM HOLDINGS BERHAD','5066.KL'))
list.append( StockCode('NWP HOLDINGS BERHAD','5025.KL'))
list.append( StockCode('NYLEX (MALAYSIA) BERHAD','4944.KL'))
list.append( StockCode('OCB BERHAD','5533.KL'))
list.append( StockCode('OCEANCASH PACIFIC BERHAD','49.KL'))
list.append( StockCode('OCK GROUP BERHAD','172.KL'))
list.append( StockCode('OCR GROUP BERHAD','7071.KL'))
list.append( StockCode('OKA CORPORATION BHD','7140.KL'))
list.append( StockCode('OLYMPIA INDUSTRIES BERHAD','3018.KL'))
list.append( StockCode('OMESTI BERHAD','9008.KL'))
list.append( StockCode('ONLY WORLD GROUP HOLDINGS BERHAD','5260.KL'))
list.append( StockCode('OPCOM HOLDINGS BERHAD','35.KL'))
list.append( StockCode('OPENSYS (M) BERHAD','40.KL'))
list.append( StockCode('ORIENTAL FOOD INDUSTRIES HOLDINGS BERHAD','7107.KL'))
list.append( StockCode('ORIENTAL HOLDINGS BERHAD','4006.KL'))
list.append( StockCode('ORIENTAL INTEREST BERHAD','5827.KL'))
list.append( StockCode('ORION IXL BERHAD','79.KL'))
list.append( StockCode('ORNAPAPER BERHAD','5065.KL'))
list.append( StockCode('OSK HOLDINGS BERHAD','5053.KL'))
list.append( StockCode('OSK VENTURES INTERNATIONAL BERHAD','53.KL'))
list.append( StockCode('OVERSEA ENTERPRISE BERHAD','153.KL'))
list.append( StockCode('P.A. RESOURCES BERHAD','7225.KL'))
list.append( StockCode('P.I.E. INDUSTRIAL BERHAD','7095.KL'))
list.append( StockCode('PACIFIC & ORIENT BERHAD','6009.KL'))
list.append( StockCode('PADINI HOLDINGS BERHAD','7052.KL'))
list.append( StockCode('PAN MALAYSIA CORPORATION BERHAD','4081.KL'))
list.append( StockCode('PAN MALAYSIA HOLDINGS BERHAD','1287.KL'))
list.append( StockCode('PANASONIC MANUFACTURING MALAYSIA BERHAD','3719.KL'))
list.append( StockCode('PANSAR BERHAD','8419.KL'))
list.append( StockCode('PANTECH GROUP HOLDINGS BERHAD','5125.KL'))
list.append( StockCode('PAOS HOLDINGS BERHAD','5022.KL'))
list.append( StockCode('PARAGON GLOBE BERHAD','3611.KL'))
list.append( StockCode('PARAGON UNION BERHAD','9407.KL'))
list.append( StockCode('PARAMOUNT CORPORATION BERHAD','1724.KL'))
list.append( StockCode('PARKSON HOLDINGS BERHAD','5657.KL'))
list.append( StockCode('PARLO BERHAD','22.KL'))
list.append( StockCode('PASDEC HOLDINGS BERHAD','6912.KL'))
list.append( StockCode('PASUKHAS GROUP BERHAD','177.KL'))
list.append( StockCode('PAVILION REAL ESTATE INVESTMENT TRUST','5212.KL'))
list.append( StockCode('PBA HOLDINGS BHD','5041.KL'))
list.append( StockCode('PCCS GROUP BERHAD','6068.KL'))
list.append( StockCode('PDZ HOLDINGS BHD','6254.KL'))
list.append( StockCode('PECCA GROUP BERHAD','5271.KL'))
list.append( StockCode('PEGASUS HEIGHTS BERHAD','4464.KL'))
list.append( StockCode('PELANGI PUBLISHING GROUP BHD.','7190.KL'))
list.append( StockCode('PELIKAN INTERNATIONAL CORPORATION BERHAD','5231.KL'))
list.append( StockCode('PENSONIC HOLDINGS BERHAD','9997.KL'))
list.append( StockCode('PENTAMASTER CORPORATION BERHAD','7160.KL'))
list.append( StockCode('PERAK CORPORATION BERHAD','8346.KL'))
list.append( StockCode('PERAK TRANSIT BERHAD','186.KL'))
list.append( StockCode('PERDANA PETROLEUM BERHAD','7108.KL'))
list.append( StockCode('PERMAJU INDUSTRIES BERHAD','7080.KL'))
list.append( StockCode('PERUSAHAAN SADUR TIMAH MALAYSIA (PERSTIMA) BHD','5436.KL'))
list.append( StockCode('PESONA METRO HOLDINGS BERHAD','8311.KL'))
list.append( StockCode('PESTECH INTERNATIONAL BERHAD','5219.KL'))
list.append( StockCode('PETERLABS HOLDINGS BERHAD','171.KL'))
list.append( StockCode('PETRA ENERGY BERHAD','5133.KL'))
list.append( StockCode('PETRON MALAYSIA REFINING & MARKETING BHD','3042.KL'))
list.append( StockCode('PETRONAS CHEMICALS GROUP BERHAD','5183.KL'))
list.append( StockCode('PETRONAS DAGANGAN BHD','5681.KL'))
list.append( StockCode('PETRONAS GAS BERHAD','6033.KL'))
list.append( StockCode('PHARMANIAGA BERHAD','7081.KL'))
list.append( StockCode('PIMPINAN EHSAN BERHAD','5622.KL'))
list.append( StockCode('PINEAPPLE RESOURCES BERHAD','6.KL'))
list.append( StockCode('PINEHILL PACIFIC BERHAD','1902.KL'))
list.append( StockCode('PINTARAS JAYA BHD','9598.KL'))
list.append( StockCode('PJBUMI BERHAD','7163.KL'))
list.append( StockCode('PLASTRADE TECHNOLOGY BERHAD','38.KL'))
list.append( StockCode('PLB ENGINEERING BERHAD','7055.KL'))
list.append( StockCode('PLENITUDE BERHAD','5075.KL'))
list.append( StockCode('PLS PLANTATIONS BERHAD','9695.KL'))
list.append( StockCode('PMB TECHNOLOGY BERHAD','7172.KL'))
list.append( StockCode('PNE PCB BERHAD','6637.KL'))
list.append( StockCode('POH HUAT RESOURCES HOLDINGS BERHAD','7088.KL'))
list.append( StockCode('POH KONG HOLDINGS BERHAD','5080.KL'))
list.append( StockCode('POLY GLASS FIBRE (M) BERHAD','8117.KL'))
list.append( StockCode('POLYMER LINK HOLDINGS BERHAD','3007.KL'))
list.append( StockCode('POS MALAYSIA BERHAD','4634.KL'))
list.append( StockCode('POWER ROOT BERHAD','7237.KL'))
list.append( StockCode('POWERWELL HOLDINGS BERHAD','217.KL'))
list.append( StockCode('PPB GROUP BERHAD','4065.KL'))
list.append( StockCode('PRESS METAL ALUMINIUM HOLDINGS BERHAD','8869.KL'))
list.append( StockCode('PRESTAR RESOURCES BERHAD','9873.KL'))
list.append( StockCode('PRESTARIANG BERHAD','5204.KL'))
list.append( StockCode('PRG HOLDINGS BERHAD','7168.KL'))
list.append( StockCode('PRICEWORTH INTERNATIONAL BERHAD','7123.KL'))
list.append( StockCode('PRINCIPAL FTSE ASEAN 40 MALAYSIA ETF','0822EA.KL'))
list.append( StockCode('PRINCIPAL FTSE CHINA 50 ETF','0823EA.KL'))
list.append( StockCode('PRIVASIA TECHNOLOGY BERHAD','123.KL'))
list.append( StockCode('PROGRESSIVE IMPACT CORPORATION BERHAD','7201.KL'))
list.append( StockCode('PROLEXUS BERHAD','8966.KL'))
list.append( StockCode('PROTASCO BERHAD','5070.KL'))
list.append( StockCode('PUBLIC BANK BERHAD','1295.KL'))
list.append( StockCode('PUBLIC PACKAGES HOLDINGS BHD','8273.KL'))
list.append( StockCode('PUC BERHAD','7.KL'))
list.append( StockCode('PUNCAK NIAGA HOLDINGS BERHAD','6807.KL'))
list.append( StockCode('PWF CORPORATION BERHAD','7134.KL'))
list.append( StockCode('QES GROUP BERHAD','196.KL'))
list.append( StockCode('QL RESOURCES BERHAD','7084.KL'))
list.append( StockCode('QUALITY CONCRETE HOLDINGS BERHAD','7544.KL'))
list.append( StockCode('RADIANT GLOBALTECH BERHAD','202.KL'))
list.append( StockCode('RALCO CORPORATION BERHAD','7498.KL'))
list.append( StockCode('RANHILL HOLDINGS BERHAD','5272.KL'))
list.append( StockCode('RAPID SYNERGY BERHAD','7765.KL'))
list.append( StockCode('RCE CAPITAL BERHAD','9296.KL'))
list.append( StockCode('REACH ENERGY BERHAD','5256.KL'))
list.append( StockCode('RED IDEAS HOLDINGS BERHAD','3002.KL'))
list.append( StockCode('RED SENA BERHAD','5270.KL'))
list.append( StockCode('REDTONE INTERNATIONAL BERHAD','32.KL'))
list.append( StockCode('RESINTECH BERHAD','7232.KL'))
list.append( StockCode('REV ASIA BERHAD','173.KL'))
list.append( StockCode('REVENUE GROUP BERHAD','200.KL'))
list.append( StockCode('REX INDUSTRY BERHAD','9946.KL'))
list.append( StockCode('REXIT BERHAD','106.KL'))
list.append( StockCode('RGB INTERNATIONAL BHD','37.KL'))
list.append( StockCode('RGT BERHAD','9954.KL'))
list.append( StockCode('RHB BANK BERHAD','1066.KL'))
list.append( StockCode('RHONE MA HOLDINGS BERHAD','5278.KL'))
list.append( StockCode('RIMBUNAN SAWIT BERHAD','5113.KL'))
list.append( StockCode('RIVERVIEW RUBBER ESTATES BERHAD','2542.KL'))
list.append( StockCode('ROHAS TECNIC BERHAD','9741.KL'))
list.append( StockCode('RUBBEREX CORPORATION (M) BERHAD','7803.KL'))
list.append( StockCode('S P SETIA BERHAD','8664.KL'))
list.append( StockCode('SALCON BERHAD','8567.KL'))
list.append( StockCode('SALUTICA BERHAD','183.KL'))
list.append( StockCode('SAM ENGINEERING & EQUIPMENT (M) BERHAD','9822.KL'))
list.append( StockCode('SAMCHEM HOLDINGS BERHAD','5147.KL'))
list.append( StockCode('SAND NISKO CAPITAL BERHAD','7943.KL'))
list.append( StockCode('SANICHI TECHNOLOGY BERHAD','133.KL'))
list.append( StockCode('SAPURA ENERGY BERHAD','5218.KL'))
list.append( StockCode('SAPURA INDUSTRIAL BERHAD','7811.KL'))
list.append( StockCode('SAPURA RESOURCES BERHAD','4596.KL'))
list.append( StockCode('SARAWAK CABLE BERHAD','5170.KL'))
list.append( StockCode('SARAWAK CONSOLIDATED INDUSTRIES BERHAD','9237.KL'))
list.append( StockCode('SARAWAK OIL PALMS BERHAD','5126.KL'))
list.append( StockCode('SARAWAK PLANTATION BERHAD','5135.KL'))
list.append( StockCode('SASBADI HOLDINGS BERHAD','5252.KL'))
list.append( StockCode('SAUDEE GROUP BERHAD','5157.KL'))
list.append( StockCode('SBC CORPORATION BERHAD','5207.KL'))
list.append( StockCode('SC ESTATE BUILDER BERHAD','109.KL'))
list.append( StockCode('SCANWOLF CORPORATION BERHAD','7239.KL'))
list.append( StockCode('SCC HOLDINGS BERHAD','158.KL'))
list.append( StockCode('SCGM BHD','7247.KL'))
list.append( StockCode('SCH GROUP BERHAD','161.KL'))
list.append( StockCode('SCICOM (MSC) BERHAD','99.KL'))
list.append( StockCode('SCIENTEX BERHAD','4731.KL'))
list.append( StockCode('SCOMI ENERGY SERVICES BHD','7045.KL'))
list.append( StockCode('SCOMI GROUP BERHAD','7158.KL'))
list.append( StockCode('SCOPE INDUSTRIES BERHAD','28.KL'))
list.append( StockCode('SDS GROUP BERHAD','212.KL'))
list.append( StockCode('SEACERA GROUP BERHAD','7073.KL'))
list.append( StockCode('SEAL INCORPORATED BERHAD','4286.KL'))
list.append( StockCode('SEALINK INTERNATIONAL BERHAD','5145.KL'))
list.append( StockCode('SECUREMETRIC BERHAD','203.KL'))
list.append( StockCode('SEDANIA INNOVATOR BERHAD','178.KL'))
list.append( StockCode('SEE HUP CONSOLIDATED BERHAD','7053.KL'))
list.append( StockCode('SEERS BERHAD','3009.KL'))
list.append( StockCode('SEG INTERNATIONAL BHD','9792.KL'))
list.append( StockCode('SELANGOR DREDGING BERHAD','2224.KL'))
list.append( StockCode('SENI JAYA CORPORATION BERHAD','9431.KL'))
list.append( StockCode('SENTORIA GROUP BERHAD','5213.KL'))
list.append( StockCode('SERBA DINAMIK HOLDINGS BERHAD','5279.KL'))
list.append( StockCode('SEREMBAN ENGINEERING BERHAD','5163.KL'))
list.append( StockCode('SERN KOU RESOURCES BERHAD','7180.KL'))
list.append( StockCode('SERSOL BERHAD','55.KL'))
list.append( StockCode('SHANGRI-LA HOTELS (MALAYSIA) BERHAD','5517.KL'))
list.append( StockCode('SHH RESOURCES HOLDINGS BERHAD','7412.KL'))
list.append( StockCode('SHIN YANG SHIPPING CORPORATION BERHAD','5173.KL'))
list.append( StockCode('SHL CONSOLIDATED BHD','6017.KL'))
list.append( StockCode('SIG GASES BERHAD','5181.KL'))
list.append( StockCode('SIGNATURE INTERNATIONAL BERHAD','7246.KL'))
list.append( StockCode('SILVER RIDGE HOLDINGS BHD','129.KL'))
list.append( StockCode('SIME DARBY BERHAD','4197.KL'))
list.append( StockCode('SIME DARBY PLANTATION BERHAD','5285.KL'))
list.append( StockCode('SIME DARBY PROPERTY BERHAD','5288.KL'))
list.append( StockCode('SIN HENG CHAN (MALAYA) BERHAD','4316.KL'))
list.append( StockCode('SINMAH CAPITAL BERHAD','9776.KL'))
list.append( StockCode('SINO HUA-AN INTERNATIONAL BERHAD','2739.KL'))
list.append( StockCode('SINOTOP HOLDINGS BERHAD','8532.KL'))
list.append( StockCode('SKB SHUTTERS CORPORATION BERHAD','7115.KL'))
list.append( StockCode('SKP RESOURCES BHD','7155.KL'))
list.append( StockCode('SL INNOVATION CAPITAL BERHAD','3008.KL'))
list.append( StockCode('SLP RESOURCES BERHAD','7248.KL'))
list.append( StockCode('SMILE-LINK HEALTHCARE GLOBAL BERHAD','3023.KL'))
list.append( StockCode('SMIS CORPORATION BERHAD','7132.KL'))
list.append( StockCode('SMRT HOLDINGS BERHAD','117.KL'))
list.append( StockCode('SMTRACK BERHAD','169.KL'))
list.append( StockCode('SOLARVEST HOLDINGS BERHAD','215.KL'))
list.append( StockCode('SOLID AUTOMOTIVE BERHAD','5242.KL'))
list.append( StockCode('SOLUTION GROUP BERHAD','93.KL'))
list.append( StockCode('SOUTH MALAYSIA INDUSTRIES BERHAD','4375.KL'))
list.append( StockCode('SOUTHERN ACIDS (M) BERHAD','5134.KL'))
list.append( StockCode('SOUTHERN STEEL BERHAD','5665.KL'))
list.append( StockCode('SPRING ART HOLDINGS BERHAD','216.KL'))
list.append( StockCode('SPRITZER BHD','7103.KL'))
list.append( StockCode('STAR MEDIA GROUP BERHAD','6084.KL'))
list.append( StockCode('STELLA HOLDINGS BERHAD','5006.KL'))
list.append( StockCode('STELLA HOLDINGS BERHAD','5006.KL'))
list.append( StockCode('STRAITS INTER LOGISTICS BERHAD','80.KL'))
list.append( StockCode('SUBUR TIASA HOLDINGS BERHAD','6904.KL'))
list.append( StockCode('SUCCESS TRANSFORMER CORPORATION BERHAD','7207.KL'))
list.append( StockCode('SUMATEC RESOURCES BERHAD','1201.KL'))
list.append( StockCode('SUNGEI BAGAN RUBBER COMPANY (MALAYA) BERHAD','2569.KL'))
list.append( StockCode('SUNSURIA BERHAD','3743.KL'))
list.append( StockCode('SUNWAY BERHAD','5211.KL'))
list.append( StockCode('SUNWAY CONSTRUCTION GROUP BERHAD','5263.KL'))
list.append( StockCode('SUNWAY REAL ESTATE INVESTMENT TRUST','5176.KL'))
list.append( StockCode('SUNZEN BIOTECH BERHAD','148.KL'))
list.append( StockCode('SUPERCOMNET TECHNOLOGIES BERHAD','1.KL'))
list.append( StockCode('SUPERGENICS BERHAD','3033.KL'))
list.append( StockCode('SUPERLON HOLDINGS BERHAD','7235.KL'))
list.append( StockCode('SUPERMAX CORPORATION BERHAD','7106.KL'))
list.append( StockCode('SUPREME CONSOLIDATED RESOURCES BERHAD','3018.KL'))
list.append( StockCode('SURIA CAPITAL HOLDINGS BERHAD','6521.KL'))
list.append( StockCode('SWS CAPITAL BERHAD','7186.KL'))
list.append( StockCode('SYARIKAT TAKAFUL MALAYSIA KELUARGA BERHAD','6139.KL'))
list.append( StockCode('SYCAL VENTURES BERHAD','9717.KL'))
list.append( StockCode('SYF RESOURCES BERHAD','7082.KL'))
list.append( StockCode('SYMPHONY LIFE BERHAD','1538.KL'))
list.append( StockCode('SYSTECH BHD','50.KL'))
list.append( StockCode('T7 GLOBAL BERHAD','7228.KL'))
list.append( StockCode('TA ANN HOLDINGS BERHAD','5012.KL'))
list.append( StockCode('TA ENTERPRISE BERHAD','4898.KL'))
list.append( StockCode('TA GLOBAL BERHAD','5158.KL'))
list.append( StockCode('TA WIN HOLDINGS BERHAD','7097.KL'))
list.append( StockCode('TADMAX RESOURCES BERHAD','4022.KL'))
list.append( StockCode('TAFI INDUSTRIES BERHAD','7211.KL'))
list.append( StockCode('TALAM TRANSFORM BERHAD','2259.KL'))
list.append( StockCode('TALIWORKS CORPORATION BERHAD','8524.KL'))
list.append( StockCode('TAMBUN INDAH LAND BERHAD','5191.KL'))
list.append( StockCode('TAN CHONG MOTOR HOLDINGS BERHAD','4405.KL'))
list.append( StockCode('TANCO HOLDINGS BERHAD','2429.KL'))
list.append( StockCode('TAS OFFSHORE BERHAD','5149.KL'))
list.append( StockCode('TASCO BERHAD','5140.KL'))
list.append( StockCode('TASEK CORPORATION BERHAD','4448.KL'))
list.append( StockCode('TASHIN HOLDINGS BERHAD','211.KL'))
list.append( StockCode('TDM BERHAD','2054.KL'))
list.append( StockCode('TECHBOND GROUP BERHAD','5289.KL'))
list.append( StockCode('TECHFAST HOLDINGS BERHAD','84.KL'))
list.append( StockCode('TECHNODEX BHD','132.KL'))
list.append( StockCode('TECK GUAN PERDANA BERHAD','7439.KL'))
list.append( StockCode('TEK SENG HOLDINGS BERHAD','7200.KL'))
list.append( StockCode('TELEKOM MALAYSIA BERHAD','4863.KL'))
list.append( StockCode('TENAGA NASIONAL BHD','5347.KL'))
list.append( StockCode('TEO GUAN LEE CORPORATION BERHAD','9369.KL'))
list.append( StockCode('TEO SENG CAPITAL BERHAD','7252.KL'))
list.append( StockCode('TEX CYCLE TECHNOLOGY (M) BERHAD','89.KL'))
list.append( StockCode('TEXCHEM RESOURCES BERHAD','8702.KL'))
list.append( StockCode('TFP SOLUTIONS BERHAD','145.KL'))
list.append( StockCode('TH HEAVY ENGINEERING BERHAD','7206.KL'))
list.append( StockCode('TH PLANTATIONS BERHAD','5112.KL'))
list.append( StockCode('THETA EDGE BERHAD','9075.KL'))
list.append( StockCode('THONG GUAN INDUSTRIES BERHAD','7034.KL'))
list.append( StockCode('THREE-A RESOURCES BERHAD','12.KL'))
list.append( StockCode('THRIVEN GLOBAL BERHAD','7889.KL'))
list.append( StockCode('TIEN WAH PRESS HOLDINGS BERHAD','7374.KL'))
list.append( StockCode('TIGER SYNERGY BERHAD','7079.KL'))
list.append( StockCode('TIMBERWELL BERHAD','7854.KL'))
list.append( StockCode('TIME DOTCOM BERHAD','5031.KL'))
list.append( StockCode('TIONG NAM LOGISTICS HOLDINGS BERHAD','8397.KL'))
list.append( StockCode('TITIJAYA LAND BERHAD','5239.KL'))
list.append( StockCode('TMC LIFE SCIENCES BERHAD','101.KL'))
list.append( StockCode('TOMEI CONSOLIDATED BERHAD','7230.KL'))
list.append( StockCode('TOMYPAK HOLDINGS BERHAD','7285.KL'))
list.append( StockCode('TONG HERR RESOURCES BERHAD','5010.KL'))
list.append( StockCode('TOP GLOVE CORPORATION BHD','7113.KL'))
list.append( StockCode('TOPVISION EYE SPECIALIST BERHAD','3013.KL'))
list.append( StockCode('TOWER REAL ESTATE INVESTMENT TRUST','5111.KL'))
list.append( StockCode('TOYO INK GROUP BERHAD','7173.KL'))
list.append( StockCode('TPC PLUS BERHAD','7176.KL'))
list.append( StockCode('TRADEPLUS HSCEI DAILY (-1X) INVERSE TRACKER','0833EA.KL'))
list.append( StockCode('TRADEPLUS HSCEI DAILY (2X) LEVERAGED TRACKER','0832EA.KL'))
list.append( StockCode('TRADEPLUS NYSE FANG+ DAILY (-1X) INVERSE TRACKER','0831EA.KL'))
list.append( StockCode('TRADEPLUS NYSE FANG+ DAILY (2X) LEVERAGED TRACKER','0830EA.KL'))
list.append( StockCode('TRADEPLUS S&P NEW CHINA TRACKER-MYR','0829EA.KL'))
list.append( StockCode('TRADEPLUS S&P NEW CHINA TRACKER-USD','0829EB.KL'))
list.append( StockCode('TRADEPLUS SHARIAH GOLD TRACKER','0828EA.KL'))
list.append( StockCode('TRANSOCEAN HOLDINGS BHD','7218.KL'))
list.append( StockCode('TRC SYNERGY BERHAD','5054.KL'))
list.append( StockCode('TRI-MODE SYSTEM (M) BERHAD','199.KL'))
list.append( StockCode('TRIVE PROPERTY GROUP BERHAD','118.KL'))
list.append( StockCode('TROPICANA CORPORATION BERHAD','5401.KL'))
list.append( StockCode('TSH RESOURCES BERHAD','9059.KL'))
list.append( StockCode('TSR CAPITAL BERHAD','5042.KL'))
list.append( StockCode('TT VISION HOLDINGS BERHAD','3020.KL'))
list.append( StockCode('TUNE PROTECT GROUP BERHAD','5230.KL'))
list.append( StockCode('TURBO-MECH BERHAD','5167.KL'))
list.append( StockCode('TURIYA BERHAD','4359.KL'))
list.append( StockCode('UCHI TECHNOLOGIES BERHAD','7100.KL'))
list.append( StockCode('UCREST BERHAD','5.KL'))
list.append( StockCode('UEM EDGENTA BERHAD','1368.KL'))
list.append( StockCode('UEM SUNRISE BERHAD','5148.KL'))
list.append( StockCode('UMS HOLDINGS BERHAD','7137.KL'))
list.append( StockCode('UMS-NEIKEN GROUP BERHAD','7227.KL'))
list.append( StockCode('UMW HOLDINGS BERHAD','4588.KL'))
list.append( StockCode('UNI WALL APS HOLDINGS BERHAD','3017.KL'))
list.append( StockCode('UNIMECH GROUP BERHAD','7091.KL'))
list.append( StockCode('UNISEM (M) BERHAD','5005.KL'))
list.append( StockCode('UNITED MALACCA BERHAD','2593.KL'))
list.append( StockCode('UNITED PLANTATIONS BERHAD','2089.KL'))
list.append( StockCode('UNITED U-LI CORPORATION BERHAD','7133.KL'))
list.append( StockCode('UOA DEVELOPMENT BHD','5200.KL'))
list.append( StockCode('UOA REAL ESTATE INVESTMENT TRUST','5110.KL'))
list.append( StockCode('UPA CORPORATION BHD','7757.KL'))
list.append( StockCode('UWC BERHAD','5292.KL'))
list.append( StockCode('UZMA BERHAD','7250.KL'))
list.append( StockCode('V.S. INDUSTRY BERHAD','6963.KL'))
list.append( StockCode('VELESTO ENERGY BERHAD','5243.KL'))
list.append( StockCode('VERSATILE CREATIVE BERHAD','4995.KL'))
list.append( StockCode('VERTICE BERHAD','7240.KL'))
list.append( StockCode('VISDYNAMICS HOLDINGS BERHAD','120.KL'))
list.append( StockCode('VITROX CORPORATION BERHAD','97.KL'))
list.append( StockCode('VIVOCOM INTL HOLDINGS BERHAD','69.KL'))
list.append( StockCode('VIZIONE HOLDINGS BERHAD','7070.KL'))
list.append( StockCode('VORTEX CONSOLIDATED BERHAD','60.KL'))
list.append( StockCode('VSOLAR GROUP BERHAD','66.KL'))
list.append( StockCode('VSTECS BERHAD','5162.KL'))
list.append( StockCode('WAH SEONG CORPORATION BERHAD','5142.KL'))
list.append( StockCode('WANG-ZHENG BERHAD','7203.KL'))

if __name__ == '__main__':
    # to manage the secret key!
    app.secret_key = 'awe2334r2rg3etg34tw3'
    app.config['SESSION_TYPE'] = 'filesystem'
    app.run(debug = True)